
strings_ru = {
    "main_screen_title": "Морской Бой",
    "letters": "АБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
    "state_press_start_game": "Правый клик - начать игру",
    "state_your_step": "Ваш ход",
    "state_your_shot_on": "Ваш выстрел по ",
    "state_opponent_shot_on": "Выстрел соперника по ",
    "state_waiting_response": "Ожидание ответа...",
    "state_waiting_opponent_step": "Ожидание хода соперника...",
    "state_opponent_first_step": "Первый ход соперника",
    "bt_fire_title": "Огонь по ",
    "away": "Мимо!",
    "wounded": "Ранен!",
    "killed": "Убит!",
    "repeated": "Было!",
    "your_ships_map": "Карта ваших кораблей:",
    "opponent_ships_map": "Карта кораблей соперника:",
    "enter_your_step": "Введите ваш ход(буква и цифра): ",
    "invalid_input": "Недопустимый ввод!",
    "invalid_letter": "Недопустимая буква!",
    "incorrect_digit": "Некорректная цифра(число)!",
    "digit_out_of_range": "Цифра(число) вне диапазона",
}

strings_en = {
    "main_screen_title": "Sea Battle",
    "letters": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "state_press_start_game": "Right click - start game",
    "state_your_step": "Your step",
    "state_your_shot_on": "Your shot on ",
    "state_opponent_shot_on": "Opponent shot on ",
    "state_waiting_response": "Waiting response...",
    "state_waiting_opponent_step": "Waiting opponent step...",
    "state_opponent_first_step": "The opponent's first step",
    "bt_fire_title": "Fire on ",
    "away": "Away!",
    "wounded": "Wounded!",
    "killed": "Killed!",
    "repeated": "It was!",
    "your_ships_map": "Your ships map:",
    "opponent_ships_map": "Opponent ships map:",
    "enter_your_step": "Enter your step(letter and number): ",
    "invalid_input": "Invalid input!",
    "invalid_letter": "Invalid letter!",
    "incorrect_digit": "Incorrect digit(number)!",
    "digit_out_of_range": "Digit(number) is out of range",
}

